---
name: Bug Report
description: File a bug report
title: "[Bug]: <title>"
labels:
  - "Type: Bug"
  - "Status: Needs Confirmation"
body:
  - type: markdown
    attributes:
      value: Before filling this bug report make sure that you tried to reproduce this on the latest's version of the mod

  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      description: Please search to see if an issue already exists for what you encountered.
      options:
        - label: I made sure to look for an existing issues
          required: true

  - type: input
    id: mod_version
    attributes:
      label: Mod Version
      placeholder: Version of the mod this bug happened on
    validations:
      required: true

  - type: textarea
    id: external
    attributes:
      label: Other Mods
      description: Did you replicate this issue with just this mod installed? If not, which other mods were involved
      placeholder: |
        None
        OR
        Example-Mod Version: 1.21.1 - 1.0.0
    validations:
      required: true

  - type: textarea
    id: modpack
    attributes:
      label: Modpack
      description: Did this issue occur while you were playing a modpack? If so what pack and version were you using?
      placeholder: |
        AllTheMods 10
        Version 4.0
    validations:
      required: false

  - type: textarea
    id: description
    attributes:
      label: What happened?
      description: Please give a thorough explanation of what happened. Attach/Link
        relevant images/files in relation to the issue!
      placeholder: I crashed :c
    validations:
      required: true

  - type: input
    id: latest-log
    attributes:
      label: Latest.Log
      description: Please upload your latest.log to https://mclo.gs/ and leave the
        link here. Note this file is different to a crash report. Located in
        `/<instance>/logs/`.
      placeholder: https://mclo.gs/...
    validations:
      required: false
