---
name: Enhancement Request
description: Request a change to a current feature
title: "[Enhancement]: <title>"
labels:
  - "Type: Enhancement"
body:
  - type: markdown
    attributes:
      value: Before filling this enhancement request make sure that you're on the latest's version of the mod

  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      description: Please search to see if an issue already exists for what you encountered.
      options:
        - label: I made sure to look for an existing issues
          required: true

  - type: textarea
    id: description
    attributes:
      label: Explain what you would like to see changed and why
      description: Please give a thorough explanation of what you would like to see changed. Attach/Link
        relevant images/files in relation to the what you want!
      placeholder: I dont like this, please change :c
    validations:
      required: true