name: Feature Request
description: Suggest a new feature or change
title: "[Feature]: "
type: feature
labels:
  - "type/request"
  - "status/unconfirmed"
body:
  - type: markdown
    attributes:
      value: |
        Provide enough detail that someone can implement this without guessing.

  - type: checkboxes
    attributes:
      label: Existing issues
      description: Search existing issues before creating a new one.
      options:
        - label: I searched for existing issues and did not find a duplicate
          required: true

  - type: dropdown
    id: side
    attributes:
      label: Side
      description: Where would this feature apply?
      options:
        - side/client
        - side/server
        - side/both
    validations:
      required: true

  - type: dropdown
    id: request_kind
    attributes:
      label: Request type
      description: Pick the best match.
      options:
        - type/enhancement
        - type/request
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem / motivation
      placeholder: What problem are you trying to solve?
    validations:
      required: true

  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
      placeholder: Describe what you want to happen.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      placeholder: What other approaches did you consider?
    validations:
      required: false

  - type: textarea
    id: extra
    attributes:
      label: Additional context
      description: Mockups, references, related mods, etc.
    validations:
      required: false