---
name: Feature Request
description: Request a new feature
title: "[Feature]: <title>"
labels:
  - "Type: Feature"
body:
  - type: markdown
    attributes:
      value: Before filling this feature request make sure that you're on the latest's version of the mod

  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      description: Please search to see if an issue already exists for what you encountered.
      options:
        - label: I made sure to look for an existing issues
          required: true

  - type: textarea
    id: description
    attributes:
      label: Explain your feature
      description: Please give a thorough explanation of what you would like to see added and why. Attach/Link
        relevant images/files in relation to the what you want!
      placeholder: I want this feature please :D
    validations:
      required: true