name: Feature Request
description: Suggest a new feature or change
title: "[Feature]: "
type: feature
labels:
  - "status/unconfirmed"
body:
  - type: markdown
    attributes:
      value: |
        Provide enough detail that someone can implement this without having to guess what you're looking for.

  - type: checkboxes
    attributes:
      label: Existing issues
      description: Search existing request before creating a new one.
      options:
        - label: I searched for existing issues and did not find a duplicate
          required: true

  - type: dropdown
    id: side
    attributes:
      label: Side
      description: Where would this feature apply? If unsure pick both.
      options:
        - side/client
        - side/server
        - side/both
    validations:
      required: true

  - type: dropdown
    id: request_kind
    attributes:
      label: Request type
      description: Pick the best match.
      options:
        - type/enhancement
        - type/request
    validations:
      required: true

  - type: textarea
    id: proposal
    attributes:
      label: Proposal 
      placeholder: Describe what you want to happen.
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Reason
      placeholder: Why do you think this feature should be added or changed?
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives
      placeholder: Did you consider any alternative solutions other than the proposed one? Can this already be solved with another mod?
    validations:
      required: false

  - type: textarea
    id: extra
    attributes:
      label: Additional context
      description: References, related mods, anything else you think may be relevant.
    validations:
      required: false
